

# Site settings
title: tell me what you need 
email: gregsadev@gmail.com
description: oh, i fuck it up, i cant wait for you to see 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: @GG
github_username:  b0rnfly

# Build settings
markdown: kramdown











